// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package db

import (
	"context"
)

const createCompany = `-- name: CreateCompany :one
insert into companies (name)
values ($1) returning id, name, created_at
`

func (q *Queries) CreateCompany(ctx context.Context, name string) (Company, error) {
	row := q.db.QueryRowContext(ctx, createCompany, name)
	var i Company
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
select id, name, created_at from companies where id = $1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id int32) (Company, error) {
	row := q.db.QueryRowContext(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
